// apps/kyb-app/src/pages/CollectionFlow/versions/v1/components/pages/Rejected/Rejected.tsx
import { useTranslation } from 'react-i18next';

import { useCustomer } from '@/components/providers/CustomerProvider';
import { Card } from '@ballerine/ui';

export const Rejected = () => {
  const { t } = useTranslation();
  const { customer } = useCustomer();

  return (
    <div className="flex h-full items-center justify-center">
      <Card className="w-full max-w-[646px] p-12">
        <div className="mb-9 flex flex-col items-center gap-9">
          <img src={customer?.logoImageUri} className="max-h-[25%] max-w-[25%]" />
          <img src="/failed-circle.svg" className="h-[100px] w-[100px]" />
        </div>
        <div className="mb-10">
          <h1 className="mb-6 text-center text-3xl font-bold leading-8">{t('rejected.header')}</h1>
          <p className="text-muted-foreground text-center text-sm leading-5 opacity-50">
            {t('rejected.content')}
            <br />
            {customer && t('contact', { companyName: customer.displayName })}
          </p>
        </div>
      </Card>
    </div>
  );
};

// examples/headless-example/src/components/Rejected.svelte
<script>
import Card from "@/components/Card.svelte";
</script>

<Card>
  <h1 class="font-bold text-center w-full text-2xl">
    Failed to verify
  </h1>
  <img src="/rejected.svg" alt="rejected" class="mx-auto mb-2"/>
  <p class="max-w-[50ch] p-1 text-center">
    Please contact support
  </p>
</Card>
