// examples/kyb-app/src/pages/CollectionFlow/components/pages/Rejected/Rejected.tsx
import { withSessionProtected } from '@app/hooks/useSignin/hocs/withSessionProtected';
import { Card } from '@ballerine/ui';

export const Rejected = withSessionProtected(() => {
  return (
    <div className="flex h-full items-center justify-center">
      <Card className="w-full max-w-[646px] p-12">
        <div className="mb-9 flex flex-col items-center gap-9">
          <img src="/public/app-logo.svg" className="h-[40px] w-[95px]" />
          <img src="/public/failed-circle.svg" className="h-[156px] w-[156px]" />
        </div>
        <div className="mb-10">
          <h1 className="mb-6 text-center text-3xl font-bold leading-8">
            Account activation rejected
          </h1>
          <p className="text-muted-foreground text-center text-sm leading-5 opacity-50">
            It seems like there was a problem with activating your account.
            <br /> For more information, please contact support at
            <br /> support@paylynk.com
          </p>
        </div>
      </Card>
    </div>
  );
});

// examples/headless-example/src/components/Rejected.svelte
<script>
import Card from "@/components/Card.svelte";
</script>

<Card>
  <h1 class="font-bold text-center w-full text-2xl">
    Failed to verify
  </h1>
  <img src="/rejected.svg" alt="rejected" class="mx-auto mb-2"/>
  <p class="max-w-[50ch] p-1 text-center">
    Please contact support
  </p>
</Card>
